title: <p align="center"> Palash Baranwal </p>
logo: /assets/img/palash.PNG

description:
  <p align="center">
  <a href="https://medium.com/@palashbaranwal">Medium</a> |
  <a href="https://www.linkedin.com/in/palashbaranwal/">LinkedIn</a> |
  <a href="https://github.com/palashbaranwal">GitHub</a>
  
  <br>   
  Data Science, Engineering And Analytics.
  Worked with - Amazon | MAQ Software | GreedyGame | Crossover
  Industry Experience - Adtech | Marketing | Supply Chain | Internal Audit 
  <br>
  </p>



theme: jekyll-theme-minimal
